set shell := ["bash", "-c"]

GO_BIN_DIR := `pwd` + "/bin"

build:
  go build -o ./target/comunicore ./cmd/comunicore
  go build -o ./target/migrate ./cmd/migrate

run +CONFIG: build
  ./target/comunicore --config {{CONFIG}}

generate-all: generate-ogen generate-sqlc

generate-ogen: install-ogen
  GOBIN={{GO_BIN_DIR}} go generate ./...

generate-sqlc: install-sqlc
  @cd internal/repository/sqlc && \
  {{GO_BIN_DIR}}/sqlc generate -f ./sqlc.yaml

install-tools: install-ogen install-sqlc

install-ogen:
  @[ ! -d {{GO_BIN_DIR}} ] || mkdir -p {{GO_BIN_DIR}}
  @if [[ ! -f {{GO_BIN_DIR}}/ogen ]]; \
  then \
    echo "Installing Ogen to {{GO_BIN_DIR}}"; \
    GOBIN={{GO_BIN_DIR}} go install github.com/ogen-go/ogen/cmd/ogen@latest; \
  fi

install-sqlc:
  @[ ! -d {{GO_BIN_DIR}} ] || mkdir -p {{GO_BIN_DIR}}
  @if [[ ! -f {{GO_BIN_DIR}}/sqlc ]]; \
  then \
    echo "Installing sqlc to {{GO_BIN_DIR}}"; \
    GOBIN={{GO_BIN_DIR}} go install github.com/sqlc-dev/sqlc/cmd/sqlc@latest; \
  fi

e2e_tests:
    @echo "Starting API e2e tests..."
    @go test -count=1 ./internal/tests/...
e2e_tests_verbose:
    @echo "Starting API e2e tests..."
    @go test ./internal/tests/... -v
e2e_tests_specific +TEST_NAME:
    @echo "Starting API e2e tests..."
    @go test ./internal/tests/e2e/... -v -run {{TEST_NAME}}
