// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AnalyticsVisitBatch struct {
	ID                 int64
	UserID             pgtype.Int4
	ClientBatchID      pgtype.UUID
	ActiveDurationMs   int64
	VisibleDurationMs  int64
	IsMobile           bool
	HadComposeActivity bool
	HadReadActivity    bool
	BatchStartAt       pgtype.Timestamptz
	BatchEndAt         pgtype.Timestamptz
	CreatedAt          pgtype.Timestamptz
}

type AuthPassword struct {
	UserID       int32
	Login        string
	PasswordHash string
}

type Post struct {
	ID        int32
	ThreadID  int32
	UserID    int32
	Content   string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type Session struct {
	SessionID pgtype.UUID
	UserID    int32
}

type Thread struct {
	ID         int32
	Title      string
	Content    string
	UserID     int32
	PostsCount int32
	CreatedAt  pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
}

type ThreadTag struct {
	ThreadID int32
	Tag      string
}

type User struct {
	ID        int32
	Name      string
	Email     string
	AvatarUrl pgtype.Text
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}
